# Generated by Django 4.1.2 on 2022-10-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinfdoshlar',
            name='added_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
