# Generated by Django 4.1.2 on 2022-10-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangolearn', '0002_sinfdoshlar_added_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinfdoshlar',
            name='added_time',
        ),
    ]
